version: "3.9"

services:
  whisper-fastapi:
    image: 214882929820.dkr.ecr.us-east-1.amazonaws.com/v5-lines/whisper-fastapi:v1.0.12
    ports:
      - "9005:9005"
    volumes:
      - ./temp:/workspace/temp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    environment:
      MODEL_NAME: "whisper-large-v3"    # or "whisper-large-v3" "whisper-medium.en" "whisper-large-v3-turbo"
      UVICORN_WORKERS: 1
      VAD_TH: 0.3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

